### PR TITLE
Make gradlew executable

### PR DESCRIPTION
**Pull request by AveryanAlex**
It is needed to run ./gradlew on unix-like systems

### CODE REVIEW

**Comment by AveryanAlex** [comment]
When you will merge pls cherry-pick to other branches

**Comment by AveryanAlex** [comment]
@Luohuayu can you cherry pick this commit to 1.18.2 and 1.16.5? Or it is better to create 2 new pull requests?

**Comment by Luohuayu** [comment]
> @Luohuayu can you cherry pick this commit to 1.18.2 and 1.16.5? Or it is better to create 2 new pull requests?

I can't do it on Windows.

**Comment by AveryanAlex** [comment]
> > @Luohuayu can you cherry pick this commit to 1.18.2 and 1.16.5? Or it is better to create 2 new pull requests?
> 
> I can't do it on Windows.

Just run git cherry-pick 53c04eaf26f3daefcb581a57728dc025f1beb860 on other branches, it will add this commit to active branch

**Pull request merged**
